version: "3"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  release:
    desc: |
      Build
          ∟ [Ex] task release VERSION=1.2.3
    deps:
      - ci
    cmds:
      - npm version {{.VERSION}}
      - bun ci
      - git push --tags
      - git push
    preconditions:
      - sh: "[ {{.VERSION}} != '' ]"
        msg: "VERSION is required."
